"use client";

import {
  useCallback,
  useEffect,
  useState,
} from "react";

import Link from "next/link";

import {
  AlertTriangle,
  ArrowRight,
  CheckCircle2,
  GitBranch,
  RefreshCw,
} from "lucide-react";

import type {
  WorkspaceManifest,
} from "@/lib/workspace-types";

import {
  apiJson,
  cx,
} from "./client";

import {
  EmptyState,
  PageIntro,
  Panel,
  Pill,
  SecondaryButton,
  Stat,
} from "./primitives";

export default function ControlCenterClient() {
  const [
    manifest,
    setManifest,
  ] = useState<WorkspaceManifest | null>(
    null,
  );

  const [loading, setLoading] =
    useState(true);

  const [error, setError] =
    useState<string | null>(null);

  const load = useCallback(
    async () => {
      setLoading(true);
      setError(null);

      try {
        const body =
          await apiJson<{
            success: boolean;
            manifest: WorkspaceManifest;
          }>(
            "/api/workspace/manifest",
          );

        setManifest(body.manifest);
      } catch (error) {
        setError(
          error instanceof Error
            ? error.message
            : "Unable to load Control Center.",
        );
      } finally {
        setLoading(false);
      }
    },
    [],
  );

  useEffect(() => {
    void load();

    const timer =
      window.setInterval(
        () => void load(),
        60_000,
      );

    return () =>
      window.clearInterval(timer);
  }, [load]);

  return (
    <div className="mx-auto flex w-full max-w-[1500px] flex-col gap-6 p-4 md:p-6">
      <PageIntro
        eyebrow="Control Center"
        title={
          manifest?.controlCenter
            .title ??
          "Operations"
        }
        description={
          manifest?.controlCenter
            .subtitle ??
          "The workspace is being resolved from your active responsibilities and workflows."
        }
        action={
          <SecondaryButton
            type="button"
            onClick={() =>
              void load()
            }
            disabled={loading}
          >
            <RefreshCw
              className={cx(
                "h-4 w-4",
                loading &&
                  "animate-spin",
              )}
            />
            Refresh
          </SecondaryButton>
        }
      />

      {error && (
        <Panel className="border-red-500/30 bg-red-500/5">
          <div className="flex items-start gap-3">
            <AlertTriangle className="mt-0.5 h-5 w-5 text-red-600" />
            <div>
              <div className="font-medium">
                Control Center could
                not resolve the
                workspace
              </div>
              <div className="mt-1 text-sm text-muted-foreground">
                {error}
              </div>
            </div>
          </div>
        </Panel>
      )}

      {!manifest && loading ? (
        <div className="grid gap-4 md:grid-cols-4">
          {[1, 2, 3, 4].map(
            (item) => (
              <div
                key={item}
                className="h-28 animate-pulse rounded-2xl border bg-muted/40"
              />
            ),
          )}
        </div>
      ) : manifest ? (
        <>
          {manifest.controlCenter
            .attention.length > 0 && (
            <Panel>
              <div className="mb-4 flex items-center justify-between">
                <div>
                  <div className="text-lg font-semibold">
                    Needs attention
                  </div>
                  <div className="text-sm text-muted-foreground">
                    Only issues
                    generated by the
                    active flows are
                    shown here.
                  </div>
                </div>

                <Pill tone="warning">
                  {
                    manifest
                      .controlCenter
                      .attention
                      .length
                  }{" "}
                  open
                </Pill>
              </div>

              <div className="divide-y divide-border">
                {manifest
                  .controlCenter
                  .attention.map(
                    (item) => (
                      <Link
                        href={
                          item.href ??
                          "/dashboard"
                        }
                        key={item.key}
                        className="flex items-center gap-4 py-3 first:pt-0 last:pb-0"
                      >
                        <div
                          className={cx(
                            "h-2.5 w-2.5 shrink-0 rounded-full",
                            item.severity ===
                              "danger"
                              ? "bg-red-500"
                              : item.severity ===
                                  "warning"
                                ? "bg-amber-500"
                                : "bg-blue-500",
                          )}
                        />

                        <div className="min-w-0 flex-1">
                          <div className="font-medium">
                            {item.title}
                          </div>

                          {item.body && (
                            <div className="text-sm text-muted-foreground">
                              {item.body}
                            </div>
                          )}
                        </div>

                        <ArrowRight className="h-4 w-4 text-muted-foreground" />
                      </Link>
                    ),
                  )}
              </div>
            </Panel>
          )}

          <div>
            <div className="mb-3 text-sm font-semibold">
              Flow metrics
            </div>

            {manifest.controlCenter
              .stats.length === 0 ? (
              <div className="rounded-xl border bg-card p-5 text-sm text-muted-foreground">
                No flow metrics are
                available yet.
              </div>
            ) : (
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                {manifest
                  .controlCenter
                  .stats.map(
                    (metric) => (
                      <Link
                        href={
                          metric.href ??
                          "/dashboard"
                        }
                        key={metric.key}
                      >
                        <Stat
                          value={
                            metric.value
                          }
                          label={
                            metric.label
                          }
                          hint={
                            metric.hint ??
                            undefined
                          }
                        />
                      </Link>
                    ),
                  )}
              </div>
            )}
          </div>

          {manifest.workflows.length >
          0 ? (
            <div>
              <div className="mb-3 text-sm font-semibold">
                Active flows
              </div>

              <div className="space-y-4">
                {manifest.workflows.map(
                  (workflow) => (
                    <Panel
                      key={
                        workflow.id
                      }
                    >
                      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                        <div>
                          <div className="flex items-center gap-2">
                            <GitBranch className="h-5 w-5" />
                            <div className="text-lg font-semibold">
                              {
                                workflow.name
                              }
                            </div>
                            <Pill tone="good">
                              Published v
                              {
                                workflow.version
                              }
                            </Pill>
                          </div>

                          {workflow.description && (
                            <p className="mt-2 text-sm text-muted-foreground">
                              {
                                workflow.description
                              }
                            </p>
                          )}
                        </div>

                        <div className="flex gap-2 text-sm">
                          <Pill tone="info">
                            {
                              workflow
                                .runtime
                                .active
                            }{" "}
                            active
                          </Pill>

                          <Pill tone="good">
                            {
                              workflow
                                .runtime
                                .completed
                            }{" "}
                            completed
                          </Pill>
                        </div>
                      </div>

                      <div className="mt-6 overflow-x-auto">
                        <div className="flex min-w-max items-stretch gap-3">
                          {workflow.steps.map(
                            (
                              step,
                              index,
                            ) => (
                              <div
                                key={
                                  step.id
                                }
                                className="flex items-center gap-3"
                              >
                                <div className="w-56 rounded-xl border bg-muted/20 p-4">
                                  <div className="text-[11px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">
                                    Step{" "}
                                    {index +
                                      1}
                                  </div>

                                  <div className="mt-1 font-medium">
                                    {
                                      step.title
                                    }
                                  </div>

                                  <div className="mt-3 grid grid-cols-2 gap-2 text-xs text-muted-foreground">
                                    <span>
                                      Ready{" "}
                                      {
                                        step
                                          .runtime
                                          .ready
                                      }
                                    </span>
                                    <span>
                                      Blocked{" "}
                                      {
                                        step
                                          .runtime
                                          .blocked
                                      }
                                    </span>
                                    <span>
                                      Waiting{" "}
                                      {
                                        step
                                          .runtime
                                          .pendingApproval
                                      }
                                    </span>
                                    <span>
                                      Done{" "}
                                      {
                                        step
                                          .runtime
                                          .completed
                                      }
                                    </span>
                                  </div>
                                </div>

                                {index <
                                  workflow
                                    .steps
                                    .length -
                                    1 && (
                                  <ArrowRight className="h-4 w-4 shrink-0 text-muted-foreground" />
                                )}
                              </div>
                            ),
                          )}
                        </div>
                      </div>
                    </Panel>
                  ),
                )}
              </div>
            </div>
          ) : (
            <EmptyState
              title="No active workflow"
              description="Create and publish a workflow. The Control Center and sidebar will rebuild themselves from it."
            />
          )}

          {manifest.controlCenter
            .quickActions.length >
            0 && (
            <div>
              <div className="mb-3 text-sm font-semibold">
                Relevant actions
              </div>

              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {manifest
                  .controlCenter
                  .quickActions.map(
                    (item) => (
                      <Link
                        href={item.href}
                        key={item.key}
                        className="rounded-xl border bg-card p-4 transition hover:bg-muted/40"
                      >
                        <div className="font-medium">
                          {item.label}
                        </div>

                        {item.description && (
                          <div className="mt-1 text-sm text-muted-foreground">
                            {
                              item.description
                            }
                          </div>
                        )}

                        <div className="mt-3 flex items-center gap-1 text-sm font-medium">
                          Open
                          <ArrowRight className="h-4 w-4" />
                        </div>
                      </Link>
                    ),
                  )}
              </div>
            </div>
          )}

          {manifest.controlCenter
            .attention.length ===
            0 &&
            manifest.workflows.length >
              0 && (
              <div className="flex items-center gap-3 rounded-xl border bg-card p-4">
                <CheckCircle2 className="h-5 w-5 text-emerald-600" />
                <div>
                  <div className="font-medium">
                    No flow bottlenecks
                    detected
                  </div>

                  <div className="text-sm text-muted-foreground">
                    The currently
                    tracked workflow
                    instances have no
                    blocked or pending
                    attention states.
                  </div>
                </div>
              </div>
            )}
        </>
      ) : (
        <EmptyState
          title="Workspace unavailable"
          description="The workspace manifest could not be resolved."
        />
      )}
    </div>
  );
}
