"use client";

import {
  useCallback,
  useEffect,
  useState,
} from "react";
import {
  Loader2,
  RefreshCw,
} from "lucide-react";

import type {
  GenericRecord,
  Responsibility,
} from "@/lib/appliance-types";
import {
  apiJson,
} from "./client";
import RecordOutput from "./record-output";
import {
  EmptyState,
  PageIntro,
  Pill,
  SecondaryButton,
} from "./primitives";

export default function DynamicWorkClient({
  responsibilityKey,
}: {
  responsibilityKey: string;
}) {
  const [responsibility, setResponsibility] =
    useState<Responsibility | null>(null);
  const [records, setRecords] =
    useState<GenericRecord[]>([]);
  const [loading, setLoading] =
    useState(true);
  const [error, setError] =
    useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const responsibilityBody = await apiJson<{
        responsibilities: Responsibility[];
      }>("/api/appliance/responsibilities");

      const normalizedKey = decodeURIComponent(responsibilityKey)
        .trim()
        .toLowerCase();

      const selected = (responsibilityBody.responsibilities ?? [])
        .find((item) =>
          item.key.toLowerCase() === normalizedKey &&
          item.isActive !== false,
        );

      if (!selected) {
        throw new Error(
          "Responsibility not found or disabled.",
        );
      }

      const recordBody = await apiJson<{
        records: GenericRecord[];
      }>(
        `/api/appliance/records?responsibilityKey=${encodeURIComponent(selected.key)}&limit=500`,
      );

      setResponsibility(selected);
      setRecords(recordBody.records ?? []);
    } catch (error) {
      setResponsibility(null);
      setRecords([]);
      setError(
        error instanceof Error
          ? error.message
          : "Unable to load Responsibility records.",
      );
    } finally {
      setLoading(false);
    }
  }, [responsibilityKey]);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <div className="mx-auto flex w-full max-w-[1500px] flex-col gap-6 p-4 md:p-6">
      <PageIntro
        eyebrow="Work"
        title={responsibility?.title ?? "Responsibility"}
        description={
          responsibility?.description ??
          "Records generated by this Responsibility. The renderer comes from the Responsibility definition."
        }
        action={
          <div className="flex items-center gap-2">
            {responsibility && (
              <Pill tone="info">
                {responsibility.definition.output.renderer.replace(/_/g, " ")}
              </Pill>
            )}
            <SecondaryButton
              type="button"
              onClick={() => void load()}
              disabled={loading}
            >
              {loading ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <RefreshCw className="h-4 w-4" />
              )}
              Refresh
            </SecondaryButton>
          </div>
        }
      />

      {loading && !responsibility ? (
        <div className="flex h-64 items-center justify-center rounded-lg border">
          <Loader2 className="h-5 w-5 animate-spin" />
        </div>
      ) : error ? (
        <EmptyState
          title="Work surface unavailable"
          description={error}
        />
      ) : responsibility ? (
        <>
          <div className="grid gap-3 sm:grid-cols-3">
            <div className="rounded-lg border bg-card p-4">
              <div className="text-2xl font-semibold">{records.length}</div>
              <div className="text-sm text-muted-foreground">records</div>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <div className="text-2xl font-semibold">
                {responsibility.definition.input.fields.length}
              </div>
              <div className="text-sm text-muted-foreground">input fields</div>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <div className="text-sm font-semibold capitalize">
                {Object.entries(responsibility.definition.crud)
                  .filter(([, enabled]) => enabled)
                  .map(([operation]) => operation)
                  .join(" · ") || "read only"}
              </div>
              <div className="text-sm text-muted-foreground">enabled operations</div>
            </div>
          </div>

          <RecordOutput
            responsibility={responsibility}
            records={records}
          />
        </>
      ) : null}
    </div>
  );
}
